### PR TITLE
Performance_tuning

### PR DESCRIPTION
**Pull request by djivey**
Tune services to support a higher rate of API saturation.

### CODE REVIEW

**Comment by djivey** [comment]
You will probably need to at least increase RAM on haproxy, memcached and mariadb to account for the amount of connections generate. I bumped cpus and ram up in all my key services during this test.

**Comment by djivey** [comment]
If you want any of those value parameterized just let me know and I can adjust

**Comment by jdiaz9** [comment]
looks good

**Comment by bitskri3g** [comment]
Have you guys had any issues with service_token_roles_required @djivey?  I've been messing with it in the 'deprecations' branch and it broke a ton of stuff, mostly around keystone in my testing.

**Comment by djivey** [comment]
> Have you guys had any issues with service_token_roles_required @djivey? I've been messing with it in the 'deprecations' branch and it broke a ton of stuff, mostly around keystone in my testing.

I haven't noticed anything, but I wasn't specifically looking for it. Its been in production for about 3 weeks here. Will take a look through the logs and make sure we just didn't overlook it.

**Comment by djivey** [comment]
@bitskri3g I don't see any issues related to service_token_roles in my env. Do you have specific errors?

**Comment by djivey** [comment]
I think you were missing this option
`service_token_roles = admin
`

**Comment by bitskri3g** [comment]
Probably - I think I read the config guide and saw that it had a default value (looks to be service) and decided to leave it implied and then spaced out and forgot that service accounts get assigned a role of 'admin', not service.

I'll let you know.

**Review by bitskri3g — COMMENTED** [review]
For the change to macros/constructor.sls in the mysql portion - you guys aren't getting deadlocks when doing multi-master writes?  Did your other adjustments to mysql make that a non-issue?

**Review by bitskri3g — COMMENTED** [review]
In haproxy.cfg, I have a slight preference for not doing jinja rendering (besides straight variable replacement) inside of the file template and like to keep that logic entirely contained in the sls for clarity (you only have to look one place to see all of your tunables and the logic behind them, so to speak).  I will adjust this, no action needed.

**Review by bitskri3g — COMMENTED** [review]
Have you guys tested the mariadb service file on both ubuntu and el8?  I vaguely remember having to disable that after they had incompatible configurations and needing to do file.line instead.  If you haven't tested it that's ok, just want to make sure that I try it out on my side.

**Comment by djivey** [comment]
> For the change to macros/constructor.sls in the mysql portion - you guys aren't getting deadlocks when doing multi-master writes? Did your other adjustments to mysql make that a non-issue?

I haven't seen any deadlocks so far after this change

**Comment by djivey** [comment]
> Have you guys tested the mariadb service file on both ubuntu and el8? I vaguely remember having to disable that after they had incompatible configurations and needing to do file.line instead. If you haven't tested it that's ok, just want to make sure that I try it out on my side.

We have not tested against el8

**Review by Chateau-Lav — APPROVED** [review]
accepting performance enhancement to kinetic in preparation for overall refresh and reorg of codebase

**Pull request merged**
